server:
  port: 8761
spring:
  application:
    name: eureka-service
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service:
      service-url: http://${eureka.instance.hostname}:${server.port}/eureka/
    server:
      waitTimeInMsWhenSyncEmpty: 5
